### PR TITLE
Swift 3

### PR DESCRIPTION
**Pull request by huwr**
Hi,

Thanks for doing the hard work of making this! I am thinking of using this for a side project I'm starting for a volunteer agency in Victoria. 

I've run a Swift 3 migration, and also added a Victorian unit test. Hope this helps!

Huw

### CODE REVIEW

**Comment by peterringset** [comment]
Hi, and thanks for your interest. The library is already compatible with Swift 3, so there's no point in integrating this PR as of now. I am however making a Swift 4-migration, and if it's okay with you I'll include your new tests.

**Comment by huwr** [comment]
Oh sure! Use what you like :)

I ran through a 'update to latest syntax' migration, but maybe it was 3.0 -> 3.1 or something. 

Good luck

**Comment by jfpseudo** [comment]
Hello!

I get this error when I try to clone the framework via terminal:

A shell task (…) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled

Any idea how I can solve this?

/Jeppe

**Comment by peterringset** [comment]
Hi @jfpseudo . This seems to be a problem with how your git-client is set up. I would suggest google for that exact error, it seems to me that your credentials are not set up correctly with your git-installation.

**Pull request closed without merging**
